# ===============================================
# Pulse AI Deployment Configuration (Render)
# Version: 1.0.0
# ===============================================
services:
  
  # 🧠 Backend — FastAPI
  # =======================
  - type: web
    name: pulse-backend
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
    startCommand: |
      cd services/backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true

    envVars:
      # Core configuration
      - key: ENV
        value: production
      - key: PORT
        value: 8080
      - key: PYTHONUNBUFFERED
        value: "1"

      # App Secrets (set manually in Render Dashboard for security)
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: VERCEL_URL
        value: https://pulse-ai-v1-0.vercel.app

  # =======================
  # 💻 Frontend — Vite
  # =======================
  - type: web
    name: pulse-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port $PORT
    autoDeploy: true

    envVars:
      # Directly reference backend URL (Render doesn’t support .url linking)
      - key: VITE_API_URL
        value: https://pulse-backend.onrender.com

      # Environment for Vite
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
