version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: pulse
      POSTGRES_PASSWORD: pulsepass
      POSTGRES_DB: pulsedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  backend:
    build:
      context: ../services/backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://pulse:pulsepass@postgres:5432/pulsedb
      - REDIS_URL=redis://redis:6379/0
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=pulse-dev
      - SUPABASE_URL=
      - SUPABASE_ANON_KEY=
      - BACKEND_SERVICE_KEY=supersecretbackendkey
      - OPENAI_API_KEY=
      - BACKEND_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ../services/backend:/app

  worker:
    build:
      context: ../services/worker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=pulse-dev
      - BACKEND_URL=http://backend:8000
      - BACKEND_SERVICE_KEY=supersecretbackendkey
      - OPENAI_API_KEY=
    depends_on:
      - redis
      - minio
      - backend
    volumes:
      - ../services/worker:/app

volumes:
  pgdata:
  miniodata:
